spring:
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: WARN
